# Generated by Django 2.2.9 on 2022-06-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220610_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text1',
            new_name='text',
        ),
    ]
