# Generated by Django 2.2.9 on 2022-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220710_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author1',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
